version: "3"
services:
  api:
    build: ./api
    volumes:
      - ./api/dist:/api/dist
    ports:
      - "8080:3000"
      - "9229:9229"
    command: npm run docker:debug
  #postgres:
  #image: postgres
  #restart: always
  #volumes:
  #- db_data:/var/lib/postgresql/data
  #graphql-engine:
  #image: hasura/graphql-engine:v1.0.0
  #ports:
  #- "8080:8080"
  #depends_on:
  #- "postgres"
  #restart: always
  #environment:
  #HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
  #HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
  #HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  #HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
#volumes:
#db_data:
